<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'MyCoinJar\Module'                        => __DIR__ . '/Module.php',
    'MyCoinJar\Controller\MyCoinJarController' => __DIR__ . '/src/MyCoinJar/Controller/MyCoinJarController.php',
    'MyCoinJar\Framework\TestCase'        => __DIR__ . '/tests/MyCoinJar/Framework/TestCase.php',
    'MyCoinJar\SampleTest'                => __DIR__ . '/tests/MyCoinJar/SampleTest.php',
);