<?php echo $this->doctype(); ?>

<!--[if IE 8]> 				 <html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->

    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('CoinJar '. $this->translate('Starter Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/offcanvas.css')
                        ->prependStylesheet($this->basePath() . '/css/foundation.css')
                        ->prependStylesheet($this->basePath() . '/css/responsive-tables.css')
                        ->prependStylesheet($this->basePath() . '/css/normalize.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/vendor/custom.modernizr.js')
            ->prependFile($this->basePath() . '/js/vendor/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="top-bar hide-for-small">
            <ul>
                <!-- Title Area -->
                <li class="name">
                    <h1>
                        <a href="">CoinJar</a>
                    </h1>
                </li>
                <li class="toggle-topbar"><a href="#"></a></li>
            </ul>
            <section>
                <!-- Right Nav Section -->
                <ul class="right">
                    <li class="show-for-small">
                        <a href="">Home</a>
                    </li>
                    <li>
                        <a href="">Exerci</a>
                    </li>
                    <li>
                        <a href="">Tation</a>
                    </li>
                    <li>
                        <a href="">Ullamcorper</a>
                    </li>
                    <li>
                        <a href="">Dolore</a>
                    </li>
                    <li>
                        <a href="">Laoreet</a>
                    </li>
                </ul>
            </section>
        </nav>
        <?php echo $this->content; ?>

<!--        <script>-->
<!--            document.write('<script src=' +-->
<!--                ('__proto__' in {} ? 'js/vendor/zepto' : 'js/vendor/jquery') +-->
<!--                '.js><\/script>')-->
<!--        </script>-->

        <script src="js/vendor/jquery.js"></script>
        <?php echo $this->inlineScript()
            ->prependFile($this->basePath() . '/js/vendor/foundation.min.js')
            ->prependFile($this->basePath() . '/js/vendor/responsive-tables.js')
        ?>
        <script>
            $(document).foundation();
        </script>
    </body>
</html>
